
server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: patient-service-route
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/v1/patients/**
