
server:
  port: 9000

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedMethods:
                  - "POST"
                  - "GET"
                  - "PUT"
                  - "DELETE"
                  - "OPTIONS"

                allowedHeaders: "**"

          routes:
            - id: auth-service-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: patient-service-route
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/api/v1/patients/**

            - id: produto-service-route
              uri: lb://PRODUTO-SERVICE
              predicates:
                - Path=/api/v1/produto/**

            - id: professional-service-route
              uri: lb://PROFESSIONAL-SERVICE
              predicates:
                - Path=/api/v1/professionals/**

            - id: specialty-service-route
              uri: lb://PROFESSIONAL-SERVICE
              predicates:
                - Path=/api/v1/specialties/**

            - id: agenda-service-route
              uri: lb://AGENDA-SERVICE
              predicates:
                - Path=/api/v1/agendamentos/**

            - id: convenios-route
              uri: lb://CONVENIO-SERVICE
              predicates:
                - Path=/api/v1/convenios/**

            - id: planos-route
              uri: lb://CONVENIO-SERVICE
              predicates:
                - Path=/api/v1/planos/**

            - id: paciente-query-route
              uri: lb://PACIENTE-CONSULTA-SERVICE
              predicates:
                - Path=/api/v1/pacientes/**
                - Method=GET

            - id: paciente-command-route
              uri: lb://PACIENTE-COMANDO-SERVICE
              predicates:
                - Path=/api/v1/pacientes/**
                - Method=POST,PUT,PATCH,DELETE