# ==========================================================
# GLOBAL DEFAULT CONFIG (applies to all profiles)
# ==========================================================

spring:
  profiles:
    active: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka