# ==========================================================
# SHARED CONFIGURATION FOR ALL SERVICES AND ALL ENVIRONMENTS
# ==========================================================

# Eureka configuration (for local development)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true