spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/vitacare_db
    username: vitacareuser
    password: vitacarepassword

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_schema

  flyway:
    enabled: true
    schemas: auth_schema
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG