spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vitacare_db
    username: vitacare_user
    password: vitacare_password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_schema

  flyway:
    enabled: true
    schemas: auth_schema
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG