spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vitacare_db
    username: vitacareuser
    password: vitacarepa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: emergencia_schema

  flyway:
    enabled: true
    schemas: emergencia_schema
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG